Some new features
Tallcraft/DeathBarrel pull request #5
Opened 2019-07-21 09:37 UTC by Ghost-chu

1. protect death barrel do not destory in the explode
2. find the space to put the barrel not directly replace the block
3. language system support

2019-07-21 20:48 UTC, Trikolon requested changes
Thanks for the PR! :smiley: 
I like the features you added and it looks really nice overall. Could you please look into the things I commented on?

2019-07-21 20:48 UTC, Trikolon commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove the IDE config files

2019-07-21 20:48 UTC, Trikolon commented on src/main/java/com/tallcraft/deathbarrel/DeathBarrel.java
> +        List<Block> blocks = new ArrayList<>(e.blockList());
Could you please explain why cloning the list is necessary here?

2019-07-21 20:48 UTC, Trikolon commented on src/main/resources/config.yml
> +msgs:
Nit: please rename to `messages`.

2019-07-21 20:48 UTC, Trikolon commented on src/main/java/com/tallcraft/deathbarrel/DeathBarrel.java
> +            if(location.getY() > 253)
This should not be hardcoded, please use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getMaxHeight--

2019-07-21 20:48 UTC, Trikolon commented on src/main/java/com/tallcraft/deathbarrel/DeathBarrel.java
> +    public void onExplode(BlockExplodeEvent e){
Duplicate?

2019-07-21 20:48 UTC, Trikolon commented on src/main/java/com/tallcraft/deathbarrel/Util.java
> +import org.apache.commons.lang.StringUtils;
I'd rather not add another dependency. Please implement this without and external library. 
[This is how I did something similar in the past](https://github.com/Tallcraft/ChatReplay/blob/de4a14ae580aa1167007d650ae7ccda18b1305ed/src/main/java/com/tallcraft/chatreplay/ChatBuffer.java#L131)

2019-07-22 07:20 UTC, Ghost-chu commented on src/main/java/com/tallcraft/deathbarrel/DeathBarrel.java
> +            if(location.getY() > 253)
Because use cloned list can directly modify original list.
If you modify original list in foreach, you will got a exception.

2019-07-22 07:20 UTC, Ghost-chu commented on src/main/java/com/tallcraft/deathbarrel/DeathBarrel.java
> +    public void onExplode(BlockExplodeEvent e){
BlockExplode(E.g Bed in nether) and EntityExplode(E.g Creeper and TNT)

2019-07-22 07:21 UTC, Ghost-chu commented on src/main/java/com/tallcraft/deathbarrel/DeathBarrel.java
> +    public void onExplode(BlockExplodeEvent e){
BlockExplode(E.g Bed in nether) and EntityExplode(E.g Creeper and TNT)

2019-07-22 07:22 UTC, Ghost-chu commented on src/main/java/com/tallcraft/deathbarrel/Util.java
> +import org.apache.commons.lang.StringUtils;
Just copied from exist code, i see you already use this lib...
Actually this is built in the Bukkit, so it's okay

2019-07-22 07:24 UTC, Ghost-chu commented on src/main/resources/config.yml
> +msgs:
Uh i'm in hospital and ready for surgery, so i hadn't computer so i can't edit this part, maybe you can modify it after merge.

2019-07-22 07:24 UTC, Ghost-chu commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Uh i'm in hospital and ready for surgery, so i hadn't computer so i can't edit this part, maybe you can modify it after merge.

2019-07-26 16:55 UTC, Trikolon commented on src/main/resources/config.yml
> +msgs:
No rush! I hope you're well. Fix this whenever you have time and then we can merge into master. :)

2019-07-26 16:57 UTC, Trikolon commented
Great work! I'm just waiting for the config key change and we can merge this. :smiley:

2019-07-28 11:11 UTC, merged

2019-07-28 11:17 UTC, Ghost-chu commented
Ah, i want push another commit...

2019-07-28 14:11 UTC, Trikolon commented
Sorry! Feel free to submit another PR